.PHONY: clean All

All:
	@echo "----------Building project:[ Inheritance_training - Debug ]----------"
	@cd "Inheritance_training" && "$(MAKE)" -f  "Inheritance_training.mk"
clean:
	@echo "----------Cleaning project:[ Inheritance_training - Debug ]----------"
	@cd "Inheritance_training" && "$(MAKE)" -f  "Inheritance_training.mk" clean
